import React,{useState}from'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,Code2,Database,FileSpreadsheet,Globe2,Mail,Menu,Phone,Search,ShieldCheck,Sparkles,UsersRound,X}from'lucide-react';import'./styles.css';
const skills=[['HTML5','Frontend',Code2],['CSS3','Frontend',Sparkles],['JavaScript','Programming',Code2],['PHP','Backend',Code2],['SQL','Database',Database],['MS Word','Productivity',FileSpreadsheet],['MS Excel','Productivity',FileSpreadsheet],['Data Entry','45 WPM typing',FileSpreadsheet],['Web Research','Research',Search],['Recruitment','Technical',UsersRound],['English Communication','Professional',Globe2],['Creativity','Problem Solving',Sparkles]];
const services=[['Web Design & Development','Responsive, clean and user-friendly websites built with modern web technologies.',Globe2],['Data Entry & Updating','Accurate data entry, formatting, updating and spreadsheet work with attention to detail.',FileSpreadsheet],['Web Research','Organized online research, information gathering and data verification for business needs.',Search],['Technical Recruitment','Support for sourcing and organizing technical candidates and recruitment information.',UsersRound]];
const certs=[['Web Development','Microsoft'],['Introduction to Cyber Security','Cisco'],['Networking Basics','AWS Academy'],['CCNA','Simplilearn | SkillUp','In Progress']];
function App(){const[open,setOpen]=useState(false);const nav=[['About','#about'],['Skills','#skills'],['Services','#services'],['Education','#education'],['Contact','#contact']];return <div className="app"><header><a className="brand" href="#home"><b>MAZ</b><span>Muhammad Ahmed Zahid</span></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([n,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{n}</a>)}<a className="talk" href="#contact">Let's Talk <ArrowUpRight size={16}/></a></nav></header><main>
<section id="home" className="hero"><div><div className="eyebrow"><i/>Available for freelance opportunities</div><h1>Certified Web Developer<br/><em>building useful digital experiences.</em></h1><p className="lead">I'm Muhammad Ahmed Zahid, a fresh and motivated web developer offering web development, data services, web research and technical recruitment support to international clients.</p><div className="actions"><a className="primary" href="#services">Explore Services <ArrowUpRight/></a><a className="secondary" href="mailto:ahmed101zahid@gmail.com">Contact Me <Mail/></a></div><div className="stats"><div><b>45</b><span>WPM typing</span></div><div><b>4</b><span>Service areas</span></div><div><b>3+</b><span>Core tech areas</span></div></div></div><div className="photo-wrap"><div className="photo"><img src="/profile.png" alt="Muhammad Ahmed Zahid"/><div className="badge"><ShieldCheck/><span>Certified<br/><small>Web Developer</small></span></div></div></div></section>
<section id="about"><div className="heading"><span>01 / ABOUT</span><h2>Fresh skills. Serious work ethic.</h2></div><div className="about"><div><p>I am a certified web developer with an ADP in Web Design & Development. As a fresh professional, I'm focused on turning my technical skills into practical solutions and building long-term relationships with clients.</p><p>My skill set combines web development with data entry, web research, communication and technical recruitment — allowing me to support clients across a range of digital and operational tasks.</p></div><aside><strong>“</strong><p>I'm new to professional freelancing, but I'm ready to learn, communicate clearly and deliver carefully.</p><small>CURRENT FOCUS</small><b>Building real-world projects & client experience</b></aside></div></section>
<section id="skills"><div className="heading"><span>02 / SKILLS</span><h2>Tools & capabilities</h2></div><div className="skills">{skills.map(([n,t,I])=><div className="skill" key={n}><i><I/></i><div><b>{n}</b><small>{t}</small></div></div>)}</div></section>
<section id="services" className="wide"><div className="heading"><span>03 / SERVICES</span><h2>How I can help</h2></div><div className="services">{services.map(([n,p,I],i)=><article key={n}><small>0{i+1}</small><I/><h3>{n}</h3><p>{p}</p><a href="#contact">Discuss a project <ArrowUpRight/></a></article>)}</div></section>
<section id="education"><div className="heading"><span>04 / EDUCATION & CERTIFICATIONS</span><h2>Learning with purpose</h2></div><div className="timeline"><article><i/> <small>EDUCATION</small><h3>ADP — Web Design & Development</h3><p>Superior University</p></article><article><i/><small>EDUCATION</small><h3>ICS</h3><p>Punjab Group of Colleges</p></article></div><div className="certs">{certs.map(([n,org,s])=><div className="cert" key={n}><ShieldCheck/><div><b>{n}</b><small>{org}</small></div>{s&&<em>{s}</em>}</div>)}</div></section>
<section className="project"><div><span>05 / PROJECTS</span><h2>Currently building my first live portfolio of work.</h2><p>I don't have completed live client projects yet because I'm starting fresh. Instead of presenting made-up client work, this portfolio keeps that transparent and will be updated as real projects are completed.</p></div><label><Sparkles/> Open to first projects</label></section>
<section id="contact" className="contact"><div><span>06 / CONTACT</span><h2>Have a project in mind?</h2><p>I'm interested in working with international clients and building long-term professional relationships.</p></div><div className="contact-card"><a href="mailto:ahmed101zahid@gmail.com"><Mail/><span><small>Email</small>ahmed101zahid@gmail.com</span><ArrowUpRight/></a><a href="tel:+923284502141"><Phone/><span><small>Phone</small>+92 328 4502141</span><ArrowUpRight/></a><div><Globe2/><span><small>Languages</small>English — Good · Urdu — Native</span></div></div></section></main><footer><span><b>MAZ</b> Muhammad Ahmed Zahid</span><small>© 2026 · Certified Web Developer</small></footer></div>};createRoot(document.getElementById('root')).render(<App/>);
